### ISSUE TITLE
CIF import broken

### ISSUE THREAD

**Issue by rokdev** [Electrostatics/pdb2pqr#146]
Hi,
The CIF import feature seems broken in the current master (c8fcfd6):

```
$ pdb2pqr30 --ff PARSE 1fas.cif 1fas.pqr
INFO:PDB2PQR v2.1.1+1323.gc8fcfd6: biomolecular structure conversion software.
INFO:Please cite:  Jurrus E, et al.  Improvements to the APBS biomolecular solvation software suite.  Protein Sci 27 112-128 (2018).
INFO:Please cite:  Dolinsky TJ, et al.  PDB2PQR: expanding and upgrading automated preparation of biomolecular structures for molecular simulations. Nucleic Acids Res 35 W522-W525 (2007).
INFO:Checking and transforming input arguments.
INFO:Loading topology files.
INFO:Loading molecule: 1fas.cif
Traceback (most recent call last):
  File "/usr/local/bin/pdb2pqr30", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/pdb2pqr/main.py", line 796, in main
    main_driver(args)
  File "/usr/local/lib/python3.8/dist-packages/pdb2pqr/main.py", line 735, in main_driver
    pdblist, is_cif = io.get_molecule(args.input_path)
  File "/usr/local/lib/python3.8/dist-packages/pdb2pqr/io.py", line 457, in get_molecule
    pdblist, errlist = cif.read_cif(input_file)
  File "/usr/local/lib/python3.8/dist-packages/pdb2pqr/cif.py", line 1037, in read_cif
    pdbdata = pdbx.load(cif_file)
  File "/usr/local/lib/python3.8/dist-packages/pdbx/__init__.py", line 23, in load
    from .reader import PdbxReader
ImportError: cannot import name 'PdbxReader' from 'pdbx.reader' (/usr/local/lib/python3.8/dist-packages/pdbx/reader/__init__.py)
```

**Comment by sobolevnrm** [comment]
Hi Robert –

Can you confirm that you’re using the latest version of the mmcif package?

Thanks,

Nathan

**Comment by rokdev** [comment]
Hi Nathan,

This is with ``mmcif_pdbx-1.1.2``.

This is on Ubuntu 20.04 with these installation steps:

```
git clone https://github.com/Electrostatics/pdb2pqr.git
cd pdb2pqr
pip3 install .
```
Thanks,

Robert

**Comment by sobolevnrm** [comment]
OK; I'll try to investigate this weekend.  Thanks for the additional information!

**Comment by sobolevnrm** [comment]
Hi @rokdev -- the PyPI package for mmcif-pdbx is messed up.  I'll be releasing a new one soon:  https://github.com/Electrostatics/mmcif_pdbx/issues/43

In the meantime, you should be able to `pip install .` from the master branch of https://github.com/Electrostatics/mmcif_pdbx to fix the problem.

Thanks

**Comment by rokdev** [comment]
Thank you, Nathan!
