### ISSUE TITLE
PDB2PQR cannot use propka on input file, 7d1t.pdb.

### ISSUE THREAD

**Issue by intendo** [Electrostatics/pdb2pqr#205]
Problem:
- When using the following command, there is an error from propka:
-- `pdb2pqr30 --ff=PARSE --titration-state-method=propka --apbs-input=7d1t.in --drop-water 7d1t.pdb 7d1t.pqr`

NOTE: Assuming you fix line 1936 in 7d1t.pdb, the output shows the following error:
```
INFO:Found O3  group:  2621-  O1   401-OEX (A) [ 126.068  184.621  180.018] O
Traceback (most recent call last):
  File "C:\Users\offo065\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\offo065\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\offo065\pnnl_work\apbs_sw_dev\sandbox\aws\win_venv\Scripts\pdb2pqr30.exe\__main__.py", line 7, in <module>
  File "c:\users\offo065\pnnl_work\apbs_sw_dev\sandbox\aws\win_venv\lib\site-packages\pdb2pqr\main.py", line 796, in main
    main_driver(args)
  File "c:\users\offo065\pnnl_work\apbs_sw_dev\sandbox\aws\win_venv\lib\site-packages\pdb2pqr\main.py", line 765, in main_driver
    is_cif=is_cif,
  File "c:\users\offo065\pnnl_work\apbs_sw_dev\sandbox\aws\win_venv\lib\site-packages\pdb2pqr\main.py", line 619, in non_trivial
    pka_df, pka_str = run_propka(args, biomolecule)
  File "c:\users\offo065\pnnl_work\apbs_sw_dev\sandbox\aws\win_venv\lib\site-packages\pdb2pqr\main.py", line 513, in run_propka
    molecule = pk_in.read_molecule_file(pdb_path, molecule)
  File "c:\users\offo065\pnnl_work\apbs_sw_dev\sandbox\aws\win_venv\lib\site-packages\propka\input.py", line 113, in read_molecule_file
    mol_container.extract_groups()
  File "c:\users\offo065\pnnl_work\apbs_sw_dev\sandbox\aws\win_venv\lib\site-packages\propka\molecular_container.py", line 81, in extract_groups
    self.conformations[name].extract_groups()
  File "c:\users\offo065\pnnl_work\apbs_sw_dev\sandbox\aws\win_venv\lib\site-packages\propka\conformation_container.py", line 63, in extract_groups
    group = is_group(self.parameters, atom)
  File "c:\users\offo065\pnnl_work\apbs_sw_dev\sandbox\aws\win_venv\lib\site-packages\propka\group.py", line 1237, in is_group
    ligand_group = is_ligand_group_by_groups(parameters, atom)
  File "c:\users\offo065\pnnl_work\apbs_sw_dev\sandbox\aws\win_venv\lib\site-packages\propka\group.py", line 1293, in is_ligand_group_by_groups
    PROTONATOR.protonate_atom(atom)
  File "c:\users\offo065\pnnl_work\apbs_sw_dev\sandbox\aws\win_venv\lib\site-packages\propka\protonate.py", line 111, in protonate_atom
    self.set_number_of_protons_to_add(atom)
  File "c:\users\offo065\pnnl_work\apbs_sw_dev\sandbox\aws\win_venv\lib\site-packages\propka\protonate.py", line 140, in set_number_of_protons_to_add
    atom.number_of_protons_to_add -= self.valence_electrons[atom.element]
KeyError: 'M'
```

It would be great if the parsers could report the line number they were parsing to help identify any input file problems.

**Comment by sobolevnrm** [comment]
I was able to successfully run [7D1T](https://www.rcsb.org/structure/7D1T) with the latest commit (f23c0e6) of PDB2PQR.
