### ISSUE TITLE
NMR proteins with hydrogens fail preparation

### ISSUE THREAD

**Issue by stefdoerr** [Electrostatics/pdb2pqr#300]
Running on PDB ID 1UNC of Villin https://www.rcsb.org/structure/1unc causes the following crash
The issue is that the residue is named GLU but it has a HE2 hydrogen which corresponds to a GLH residue. Then pdb2pqr crashes because it's GLU template doesn't have a bond to any HE2 hydrogens.
Do you have any plans on fixing this? In the meanwhile I will make my own patches but just wanted to point out the issue.

```
CRITICAL:Unable to debump biomolecule. Biomolecular structure is incomplete:  Found gap in biomolecule structure for atom ATOM     71  HE2 GLU     4      -6.532   5.076  -6.540  0.0000 0.0000
CRITICAL:Giving up.
Traceback (most recent call last):
  File "/home/sdoerr/miniconda3/envs/htmd3.9/lib/python3.9/site-packages/pdb2pqr/debump.py", line 148, in debump_biomolecule
    self.biomolecule.set_reference_distance()
  File "/home/sdoerr/miniconda3/envs/htmd3.9/lib/python3.9/site-packages/pdb2pqr/biomolecule.py", line 483, in set_reference_distance
    raise ValueError(
ValueError: Found gap in biomolecule structure for atom ATOM     71  HE2 GLU     4      -6.532   5.076  -6.540  0.0000 0.0000
```
![image](https://user-images.githubusercontent.com/7935362/151138547-72e03793-cf32-4a6f-b093-7a5b4444362b.png)

**Comment by sobolevnrm** [comment]
@stefdoerr -- are you able to share the patches you mentioned above?  Thanks.

**Comment by stefdoerr** [comment]
https://github.com/Acellera/moleculekit/blob/main/moleculekit/tools/preparation.py#L475-L491
It's a bit specific to my library though. But the main idea is simply to check some residues if they have atoms which correspond to a specific protonation and if that's the case, rename them to that protonation state.
