### ISSUE TITLE
CIF Read Error: AttributeError: 'NoneType' object has no attribute 'get_value'

### ISSUE THREAD

**Issue by jacob-r-anderson** [Electrostatics/pdb2pqr#303]
Running pdb2pqr 3.4.1 on Ubuntu 18.04.

I saved a molecular model in CIF format using ChimeraX. When I try to use pdb2pqr, I get the error:

```
pdb2pqr30 --titration-state-method propka --with-ph 5.2 --ff AMBER --keep-chain input.cif out.pqr
INFO:PDB2PQR v3.4.1: biomolecular structure conversion software.
INFO:Please cite:  Jurrus E, et al.  Improvements to the APBS biomolecular solvation software suite.  Protein Sci 27 112-128 (2018).
INFO:Please cite:  Dolinsky TJ, et al.  PDB2PQR: expanding and upgrading automated preparation of biomolecular structures for molecular simulations. Nucleic Acids Res 35 W522-W525 (2007).
INFO:Checking and transforming input arguments.
INFO:Loading topology files.
INFO:Loading molecule: input.cif
Traceback (most recent call last):
  File "/home/jranderson/miniconda3/envs/phylo_env/bin/pdb2pqr30", line 10, in <module>
    sys.exit(main())
  File "/home/jranderson/miniconda3/envs/phylo_env/lib/python3.8/site-packages/pdb2pqr/main.py", line 820, in main
    if main_driver(args) == 1:
  File "/home/jranderson/miniconda3/envs/phylo_env/lib/python3.8/site-packages/pdb2pqr/main.py", line 757, in main_driver
    pdblist, is_cif = io.get_molecule(args.input_path)
  File "/home/jranderson/miniconda3/envs/phylo_env/lib/python3.8/site-packages/pdb2pqr/io.py", line 456, in get_molecule
    pdblist, errlist = cif.read_cif(input_file)
  File "/home/jranderson/miniconda3/envs/phylo_env/lib/python3.8/site-packages/pdb2pqr/cif.py", line 1040, in read_cif
    head_pdb, head_err = header(block)
  File "/home/jranderson/miniconda3/envs/phylo_env/lib/python3.8/site-packages/pdb2pqr/cif.py", line 447, in header
    ridd = database_obj.get_value("recvd_initial_deposition_date")
AttributeError: 'NoneType' object has no attribute 'get_value'

```

Is this an error interpreting the CIF?

**Comment by sobolevnrm** [comment]
Please attach the CIF file so we can troubleshoot.  Thank you.

**Comment by sobolevnrm** [comment]
I'm closing this but will reopen if @jacob-r-anderson posts the CIF file that caused the problem.
