### ISSUE TITLE
error during conversion of pdb file to pqr file format

### ISSUE THREAD

**Issue by rubinanoor9** [Electrostatics/pdb2pqr#313]
Hi pdb2pqr user!
I have complex structure of receptor and ligand in the pdb format. I am trying to convert this pdb file into pqr file format for binding energy calculation. During running command line:
pdb2pqr30 --ff=AMBER complex.pdb complex.pqr --ligand=lig.mol2

I got following error:
INFO:PDB2PQR v3.5.2: biomolecular structure conversion software.
INFO:Please cite:  Jurrus E, et al.  Improvements to the APBS biomolecular solvation software suite.  Protein Sci 27 112-128 (2018).
INFO:Please cite:  Dolinsky TJ, et al.  PDB2PQR: expanding and upgrading automated preparation of biomolecular structures for molecular simulations. Nucleic Acids Res 35 W522-W525 (2007).
INFO:Checking and transforming input arguments.
INFO:Loading topology files.
INFO:Loading molecule: complex.pdb
INFO:Setting up molecule.
WARNING:Unable to find amino or nucleic acid definition for MN.  Parsing as new residue.
WARNING:Unable to find amino or nucleic acid definition for MN.  Parsing as new residue.
WARNING:Unable to find amino or nucleic acid definition for MOL.  Parsing as new residue.
INFO:Created biomolecule object with 372 residues and 5787 atoms.
INFO:Setting termini states for biomolecule chains.
INFO:Loading forcefield.
INFO:Loading hydrogen topology definitions.
INFO:This biomolecule is clean.  No repair needed.
INFO:Updating disulfide bridges.
INFO:Debumping biomolecule.
INFO:Adding hydrogens to biomolecule.
INFO:Debumping biomolecule (again).
INFO:Optimizing hydrogen bonds
INFO:Applying force field to biomolecule states.
INFO:Processing ligand.
WARNING:Using ZAP9 forcefield for ligand radii.
Traceback (most recent call last):
  File "/home/rubina/miniconda3/bin/pdb2pqr30", line 8, in <module>
    sys.exit(main())
  File "/home/rubina/miniconda3/lib/python3.7/site-packages/pdb2pqr/main.py", line 822, in main
    if main_driver(args) == 1:
  File "/home/rubina/miniconda3/lib/python3.7/site-packages/pdb2pqr/main.py", line 790, in main_driver
    is_cif=is_cif,
  File "/home/rubina/miniconda3/lib/python3.7/site-packages/pdb2pqr/main.py", line 665, in non_trivial
    ligand.assign_parameters()
  File "/home/rubina/miniconda3/lib/python3.7/site-packages/pdb2pqr/ligand/mol2.py", line 330, in assign_parameters
    self.assign_charges()
  File "/home/rubina/miniconda3/lib/python3.7/site-packages/pdb2pqr/ligand/mol2.py", line 348, in assign_charges
    atom.charge = atom.formal_charge
  File "/home/rubina/miniconda3/lib/python3.7/site-packages/pdb2pqr/ligand/mol2.py", line 236, in formal_charge
    nonbonded = NONBONDED_BY_TYPE[self.type]
KeyError: 'C'

and when we eliminate mol2 file of the ligand and use command line;
pdb2pqr30 --ff=AMBER complex.pdb complex.pqr
It generate pqr file of only protein residues and they also does not consider MN (manganese) in it.
I am looking forward to hear from you.
Thanks in adavance
Regards
 #Rubina

**Comment by sobolevnrm** [comment]
Can you please provide the PDB and MOL2 file that generated the problem?  Thank you.

**Comment by rubinanoor9** [comment]
Kindly find the attach file

[apbs-input-file.zip](https://github.com/Electrostatics/pdb2pqr/files/8597345/apbs-input-file.zip)
