### ISSUE TITLE
Error message heavy atoms missing

### ISSUE THREAD

**Issue by bakpaotlrasin** [Electrostatics/pdb2pqr#361]
The protein 4xis is showing this error message, how could I resolve this? 
Any help would be appreciated. Thank you :)

CRITICAL:Too few atoms present to reconstruct or cap residue GLY A 388 in structure! This error is generally caused by missing backbone atoms in this biomolecule; you must use an external program to complete gaps in the biomolecule backbone. Heavy atoms missing from GLY A 388:  C O OXT CA
CRITICAL:Giving up.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pdb2pqr/main.py", line 792, in main_driver
    results = non_trivial(
  File "/usr/local/lib/python3.8/dist-packages/pdb2pqr/main.py", line 622, in non_trivial
    biomolecule.repair_heavy()
  File "/usr/local/lib/python3.8/dist-packages/pdb2pqr/biomolecule.py", line 1071, in repair_heavy
    raise ValueError(err)
ValueError: Too few atoms present to reconstruct or cap residue GLY A 388 in structure! This error is generally caused by missing backbone atoms in this biomolecule; you must use an external program to complete gaps in the biomolecule backbone. Heavy atoms missing from GLY A 388:  C O OXT CA

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/pdb2pqr30", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/pdb2pqr/main.py", line 829, in main
    if main_driver(args) == 1:
  File "/usr/local/lib/python3.8/dist-packages/pdb2pqr/main.py", line 802, in main_driver
    raise RuntimeError from err
RuntimeError

**Comment by sobolevnrm** [comment]
Hello --

As mentioned in [REMARK 470 of the PDB file](https://files.rcsb.org/header/4XIS.pdb), this structure is missing some heavy atoms.  Unfortunately, there are too many missing atoms for PDB2PQR to repair so it terminated with the error you saw.

Sorry we can't help to resolve this.
