### ISSUE TITLE
ValueError: 'P' is not in list

### ISSUE THREAD

**Issue by GuhLelouch** [Electrostatics/pdb2pqr#369]
Hi all,

When I run PDB2PQR (web) with my protein and a ligand, the .pqr file is not generated and the following error is shown in pdb2pqr.stderr.txt:

```
--------------------------------------------------------------------------------------------------------
INFO:Applying pKa values at a pH of 7.00:
WARNING:PDB2PQR could not identify the following residues and residue numbers as returned by PROPKA or PDB2PKA
WARNING:             ACO 393 B
INFO:Adding hydrogens to biomolecule.
INFO:Debumping biomolecule (again).
INFO:Optimizing hydrogen bonds
INFO:Applying force field to biomolecule states.
INFO:Processing ligand.
WARNING:Using ZAP9 forcefield for ligand radii.
CRITICAL:'P' is not in list
CRITICAL:Giving up.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pdb2pqr/main.py", line 792, in main_driver
    results = non_trivial(
  File "/usr/local/lib/python3.8/dist-packages/pdb2pqr/main.py", line 672, in non_trivial
    ligand.assign_parameters()
  File "/usr/local/lib/python3.8/dist-packages/pdb2pqr/ligand/mol2.py", line 330, in assign_parameters
    self.assign_charges()
  File "/usr/local/lib/python3.8/dist-packages/pdb2pqr/ligand/mol2.py", line 348, in assign_charges
    atom.charge = atom.formal_charge
  File "/usr/local/lib/python3.8/dist-packages/pdb2pqr/ligand/mol2.py", line 294, in formal_charge
    p_atom = self.bonds[0].atoms[elements.index("P")]
ValueError: 'P' is not in list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/pdb2pqr30", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/pdb2pqr/main.py", line 829, in main
    if main_driver(args) == 1:
  File "/usr/local/lib/python3.8/dist-packages/pdb2pqr/main.py", line 802, in main_driver
    raise RuntimeError from err
RuntimeError
```
Another user had the same problem with "ValueError: 'P' is not in list" in May, but apparently there was no conclusion on how to solve it. However, in my case, the ligand does contain P atoms.

I appreciate any help you may provide.

Best regards,

Gustavo

**Comment by sobolevnrm** [comment]
Can you provide a PDB ID for a structure that generates this error?

**Comment by GuhLelouch** [comment]
I encountered the same error again, but this time on my installation instead of the web server. The ligands that I want to process belong to the PDB ID 1M3Z.
