### ISSUE TITLE
Error to process neutral Cter of ASN 

### ISSUE THREAD

**Issue by micmar15sr** [Electrostatics/pdb2pqr#386]
When i process a pdb file obtained from a protein modelled with Charmm36m topology extracted from a trajectory by the gmx trjconv software I obtain the following error:

```powershell
ValueError: Biomolecular structure is incomplete:  Found gap in biomolecule structure for atom ATOM   2654  HT2 ASN   166      72.292  57.589  76.447  0.0000 0.0000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marcello/anaconda3/envs/propka/lib/python3.11/site-packages/pdb2pqr/main.py", line 792, in main_driver
    results = non_trivial(
              ^^^^^^^^^^^^
  File "/home/marcello/anaconda3/envs/propka/lib/python3.11/site-packages/pdb2pqr/main.py", line 631, in non_trivial
    raise ValueError(err)
ValueError: Unable to debump biomolecule. Biomolecular structure is incomplete:  Found gap in biomolecule structure for atom ATOM   2654  HT2 ASN   166      72.292  57.589  76.447  0.0000 0.0000

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/marcello/anaconda3/envs/propka/bin/pdb2pqr30", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/marcello/anaconda3/envs/propka/lib/python3.11/site-packages/pdb2pqr/main.py", line 829, in main
    if main_driver(args) == 1:
       ^^^^^^^^^^^^^^^^^
  File "/home/marcello/anaconda3/envs/propka/lib/python3.11/site-packages/pdb2pqr/main.py", line 802, in main_driver
    raise RuntimeError from err
RuntimeError

``` 

It seems that renaming the "HT2" atom to "H  ", make the program work (properly??). I saw older issue that are related to the  *.xml files, maybe there are some changes needed but i'm not able to undertand if is just related to add another <altname\> or create another group.

**Comment by sobolevnrm** [comment]
Thank you for bringing this up.  I need to fix #367 before I can address this problem.

**Comment by micmar15sr** [comment]
Ok, thank you, does modifying the PDB as I did make it work properly? Is there a guide to understand and maybe try to modify the xml file on my own properly and then suggest a commit?  Could you suggest some clue on the file to modify?

**Comment by sobolevnrm** [comment]
I am unable to fix this right now, unfortunately.
