### ISSUE TITLE
Ligand amide bond type not

### ISSUE THREAD

**Issue by and-tos** [Electrostatics/pdb2pqr#394]
I am getting the following error when trying to assign protonation states to PDB 3ptg along with the ligand. Am I doing something wrong or is this just a limitation of the program?

`INFO:PDB2PQR v3.6.1: biomolecular structure conversion software.
INFO:Please cite:  Jurrus E, et al.  Improvements to the APBS biomolecular solvation software suite.  Protein Sci 27 112-128 (2018).
INFO:Please cite:  Dolinsky TJ, et al.  PDB2PQR: expanding and upgrading automated preparation of biomolecular structures for molecular simulations. Nucleic Acids Res 35 W522-W525 (2007).
INFO:Checking and transforming input arguments.
INFO:Loading topology files.
INFO:Loading molecule: 3ptg.pdb
INFO:Setting up molecule.
Traceback (most recent call last):
  File "/usr/local/bin/pdb2pqr30", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/pdb2pqr/main.py", line 829, in main
    if main_driver(args) == 1:
  File "/usr/local/lib/python3.8/dist-packages/pdb2pqr/main.py", line 771, in main_driver
    biomolecule, definition, ligand = setup_molecule(
  File "/usr/local/lib/python3.8/dist-packages/pdb2pqr/main.py", line 404, in setup_molecule
    ligand.read(ligand_file)
  File "/usr/local/lib/python3.8/dist-packages/pdb2pqr/ligand/mol2.py", line 458, in read
    mol2_file = self.parse_bonds(mol2_file)
  File "/usr/local/lib/python3.8/dist-packages/pdb2pqr/ligand/mol2.py", line 551, in parse_bonds
    raise NotImplementedError(
NotImplementedError: PDB2PQR does not currently support the amide (am) bond type.`

**Comment by sobolevnrm** [comment]
Unfortunately, this is likely a limitation of the program.
